# Generated by Django 4.0.4 on 2022-05-30 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_calificacion_compraproducto_usuario_delete_persona_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='id',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='idCalificacion',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AlterField(
            model_name='compraproducto',
            name='idCompra',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id contacto'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id donacion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
