# Generated by Django 4.0.4 on 2022-05-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_calificacion_id_calificacion_idcalificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='idCalificacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
