# Generated by Django 4.0.4 on 2022-06-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_calificacion_idcalificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='texto',
            new_name='mensaje',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='puntuacionProm',
            field=models.IntegerField(default=True, null=True),
        ),
    ]
