# Generated by Django 4.0.4 on 2022-06-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_contacto_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroPrecios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='contacto',
            name='checkOfertas',
            field=models.BooleanField(verbose_name='Recibir informacion'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
