# Generated by Django 4.0.4 on 2022-06-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_filtroprecios_alter_calificacion_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='idCalificacion',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='calificacion',
            old_name='idUsuario',
            new_name='usuario',
        ),
    ]
