# Generated by Django 4.0.4 on 2022-06-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id suscripcion')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha', models.DateField(auto_now=True)),
                ('telefono', models.IntegerField()),
                ('monto', models.IntegerField()),
                ('checkInforme', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoSuscripcion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id tipo de suscripcion')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre tipo de suscripcion')),
            ],
        ),
        migrations.DeleteModel(
            name='Donacion',
        ),
        migrations.DeleteModel(
            name='TipoDonacion',
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='tipoSuscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tiposuscripcion'),
        ),
    ]
