# Generated by Django 4.0.4 on 2022-06-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_tiposuscripcion_suscripcion_tipo_suscripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscripcion',
            old_name='checkInforme',
            new_name='recibe_informe',
        ),
    ]
