# Generated by Django 4.0.4 on 2022-06-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_suscripcion_estado_suscripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscripcion',
            old_name='estado_suscripcion',
            new_name='estado',
        ),
    ]
