# Generated by Django 4.0.4 on 2022-06-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_detallecarrito_subtotal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompraProducto',
        ),
    ]
