# Generated by Django 4.0.4 on 2022-06-24 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0045_compra_estadopedido_pedido_detallecompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcion',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='telefono',
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='suscriptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.estadopedido'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
