# Generated by Django 4.0.4 on 2022-06-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_cambioestadopedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_cierre',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
