# Generated by Django 4.0.4 on 2022-06-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_historialestadopedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestadopedido',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
