# Generated by Django 4.0.4 on 2022-06-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_suscripcion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposuscripcion',
            name='desc',
            field=models.IntegerField(default=0, verbose_name='Porcentaje de descuento'),
        ),
    ]
