# Generated by Django 4.0.4 on 2022-05-30 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_persona_dv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='CategoriaProducto',
        ),
    ]
