# Generated by Django 4.0.4 on 2022-05-30 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_categoria_categoriaproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsuntoContacto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id asunto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre asunto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDonacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id tipo de donacion')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre tipo de donacion')),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id donacion')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('celular', models.IntegerField()),
                ('monto', models.IntegerField()),
                ('checkInforme', models.BooleanField()),
                ('tipoDonacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipodonacion')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id contacto')),
                ('correo', models.CharField(max_length=50)),
                ('texto', models.TextField(max_length=500)),
                ('checkOfertas', models.BooleanField()),
                ('fecha', models.DateField()),
                ('asunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asuntocontacto')),
            ],
        ),
    ]
