# Generated by Django 4.0.4 on 2022-06-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_idcalificacion_calificacion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='puntuacion',
            field=models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5']]),
        ),
    ]
