# Generated by Django 4.0.4 on 2022-06-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_donacion_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donacion',
            old_name='celular',
            new_name='telefono',
        ),
    ]
