# Generated by Django 4.0.4 on 2022-06-07 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_celular_donacion_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='puntuacionProm',
            new_name='puntuacion_avg',
        ),
    ]
