# Generated by Django 4.0.4 on 2022-06-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_rename_checkinforme_suscripcion_recibe_informe'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='estado_suscripcion',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='recibe_informe',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
