# Generated by Django 4.0.4 on 2022-06-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_rename_estado_suscripcion_suscripcion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
