# Generated by Django 4.0.4 on 2022-06-29 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_tiposuscripcion_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descuento', models.IntegerField(default=0)),
                ('mensaje', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='promocion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.promocion'),
        ),
    ]
