# Generated by Django 4.0.4 on 2022-06-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_producto_precio_promocional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
