# Generated by Django 4.0.4 on 2022-06-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_promocion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='mensaje',
            field=models.CharField(max_length=100),
        ),
    ]
