# Generated by Django 4.0.4 on 2022-06-29 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_promocion_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='promocion',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.promocion'),
        ),
    ]
