# Generated by Django 4.0.4 on 2022-06-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_producto_promocion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='descuento',
            field=models.IntegerField(),
        ),
    ]
