# Generated by Django 4.0.4 on 2022-06-30 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_producto_precio_promocional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcion',
            name='estado',
        ),
    ]
